GET  http://localhost:4545/alert-api/budgetAlert
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZjlhMmU1NDNiOWNhNzljMTAyMGViNCIsImVtYWlsIjoidXNlNEBnbWFpbC5jb20iLCJOYW1lIjoidXNlcjQiLCJpYXQiOjE3NzgwNDQ3MzMsImV4cCI6MTc3ODA0ODMzM30.7kKgEmOPYuI7uA_YS_6POd1FWQwqQi2PuzwwRMtskIs