POST http://localhost:4545/budget-api/addlimit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZjlhMmU1NDNiOWNhNzljMTAyMGViNCIsImVtYWlsIjoidXNlNEBnbWFpbC5jb20iLCJOYW1lIjoidXNlcjQiLCJpYXQiOjE3NzgwMzkzNjksImV4cCI6MTc3ODA0Mjk2OX0.FomhHMpdGP1kn6xwWMdDAO6Koy3UKDCzLQfpe9J2QVA

{
    "category":"Transport",
    "limit" :5000
}

###
GET http://localhost:4545/budget-api/checklimit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZjlhMmU1NDNiOWNhNzljMTAyMGViNCIsImVtYWlsIjoidXNlNEBnbWFpbC5jb20iLCJOYW1lIjoidXNlcjQiLCJpYXQiOjE3NzgwMzkzNjksImV4cCI6MTc3ODA0Mjk2OX0.FomhHMpdGP1kn6xwWMdDAO6Koy3UKDCzLQfpe9J2QVA


###
PUT http://localhost:4545/budget-api/editlimit/69f98d7f46796e84385ee157
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZjlhMmU1NDNiOWNhNzljMTAyMGViNCIsImVtYWlsIjoidXNlNEBnbWFpbC5jb20iLCJOYW1lIjoidXNlcjQiLCJpYXQiOjE3NzgwMzkzNjksImV4cCI6MTc3ODA0Mjk2OX0.FomhHMpdGP1kn6xwWMdDAO6Koy3UKDCzLQfpe9J2QVA

{
    "category":"Shopping",
    "limit":4000
}


###
DELETE http://localhost:4545/budget-api/deletelimit/69f98d7f46796e84385ee157
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZjlhMmU1NDNiOWNhNzljMTAyMGViNCIsImVtYWlsIjoidXNlNEBnbWFpbC5jb20iLCJOYW1lIjoidXNlcjQiLCJpYXQiOjE3NzgwMzkzNjksImV4cCI6MTc3ODA0Mjk2OX0.FomhHMpdGP1kn6xwWMdDAO6Koy3UKDCzLQfpe9J2QVA
