GET http://localhost:4545/insights-api/getInsights
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmFkMWY0NzU2NGEyZDVhZmJlZGRhNyIsImVtYWlsIjoidXNlNUBnbWFpbC5jb20iLCJOYW1lIjoidXNlcjUiLCJpYXQiOjE3NzgwNDcxOTksImV4cCI6MTc3ODA1MDc5OX0.Xkb31F8Ds3m98Hqfa7IREEbyocsI6YQ4KrkpIUlFOp4